path=(
/usr/local/bin(N-/)
/usr/local/sbin(N-/)
/opt/local/bin(N-/)
/opt/local/sbin(N-/)
/opt/homebrew/bin(N-/)
/opt/homebrew/sbin(N-/)
${path}
)

manpath=(
/usr/share/man(N-/)
/usr/local/share/man(N-/)
/usr/X11/share/man(N-/)
/opt/local/share/man(N-/)
/opt/homebrew/share/man(N-/)
${manpath}
)
